### ISSUE TITLE
How can I change the font to OCRB font for my payslip print?

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#277]
How can I change the font to OCRB font for my payslip print?

**Comment by diezcode** [comment]
I see the OCRB font is in static/fonts in the payment slip module.
How can I use that for the print of the payment in odoo8?

**Comment by yvaucher** [comment]
@diezcode You mean that you want to use the font in an other report like Qweb ?

If so you can define a style in css.

Something like:

``` xml
  <div class="page">
    <style>
      @font-face
      {
        font-family: "OCRB";
        font-style: normal;
        font-weight: normal;
        src: url('/specific_product_label/static/src/font/ocrbb.ttf') format('truetype');
      }
    </style>
    <!-- content -->
  </div>
```

This is quite the same as in [webkit version](https://github.com/OCA/l10n-switzerland/blob/7.0/l10n_ch_payment_slip/report/multi_bvr.mako#L5) just change the path.

Otherwise here is where the font is registered: https://github.com/OCA/l10n-switzerland/blob/10.0/l10n_ch_payment_slip/models/payment_slip.py#L380
Thus you could alter some part of the reportlab generation to use this font for any text.

**Comment by diezcode** [comment]
I use the payment slip modul. I print it normal with the button that the modul imports.
How can I see if there is the ocrb font?

**Comment by yvaucher** [comment]
@diezcode This is already used by default in the printout.

You can activate "Insert BVR background ?" in company settings.
This will show you if everything is correctly placed.

If you check properties of the PDF you should also see OCR-B-Bold font in it.
