### ISSUE TITLE
[9.0] l10n_ch German (CH) translation does not work (i18n_extra file)

### ISSUE THREAD

**Issue by lucode** [OCA/l10n-switzerland#296]
Not: This is no related to a module on this repo, but from the Odoo repo.
A couple of people experience the same bug and a really usefull workaround hasn't be found yet.
The German transalation in i18n_extra (Table of account/ Taxes) is only be used if the set language is de_DE, with de_CH there is no way to make it work. see:
https://www.odoo.com/forum/help-1/question/german-translation-of-swiss-chart-of-accounts-not-working-91132

**Comment by treviser** [comment]
de_CH is not a supported language. It should not be available in the first place.

**Comment by yvaucher** [comment]
This might be an issue in Odoo core. In fact sub languages like de_CH should inherit from the main language (de_DE) but as translations with l10n_multilang module for chart of account behave differently this might not work as expected. You should open a bug report on https://github.com/odoo/odoo/issues

The work around is to use de_DE instead of de_CH, by the way I'm not aware of any existing translations in de_CH you might not see the difference.

**Comment by treviser** [comment]
de_CH is not available in transifex.

**Comment by yvaucher** [comment]
@treviser it is intended as you don't need to translate everything in de_CH you should only create translation for differences from de_DE

**Comment by treviser** [comment]
I know.
