### ISSUE TITLE
V10: can't validate a payment order if a CCP number is required but missing on the res.partner.bank

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/l10n-switzerland#378]
Hi

The problem is that in such a case, the message that should have popped is trying to get the value of the "name" field of that res.partner.bank object.
Located here:
l10n_ch_pain_base/models/account_payment_order.py, line 94
Whereas at line 77 it's correct.

**Comment by yvaucher** [comment]
I had hard time to understand what you meant with your issue title, I guess you mean that it fails to raise the UserError message.
As in place it would raise an other exception because a `res.partner.bank` has no `name` field. So the patch needs to take the bank name instead of the partner_bank name is what you meant but here the check is indeed on the `res.partner.bank` thus showing the `acc_number` should be fine.

Thanks for reporting.

**Comment by yvaucher** [comment]
Closed as fixed by https://github.com/OCA/l10n-switzerland/pull/383
