### ISSUE TITLE
Import file .v11: error "AttributeError: 'bool' object has no attribute 'id'.

### ISSUE THREAD

**Issue by jmburri** [OCA/l10n-switzerland#473]
![v11_error](https://user-images.githubusercontent.com/34301568/54194660-0b43a100-44bd-11e9-9dde-aa822e3a4410.png)
Hello,

I have a problem when I import .v11 files. Sometimes, when a line of file match with an invoice which is already paid, I have the following error: Import file .v11: error "AttributeError: 'bool' ofject has no attribute 'id'.

Maybe someone may help me ?

Thanks in advance.

**Comment by yvaucher** [comment]
@jmburri this seems a very old version of import v11 module (OpenERP 7.0?). The error suggests it doesn't find an account.

https://github.com/OCA/l10n-switzerland/blob/7.0/l10n_ch_payment_slip/wizard/bvr_import.py#L196

Your partners are probably missing a value in `property_account_payable` or `property_account_receivable`

You could propose a patch to deal better with a case of missing value in those fields.
Nevertheless, I suggest you to migrate your Odoo instance because v11 will disappear in favor or ISO20022. And AFAIK there is no fully working version of ISO20022 for the swiss implementation in OpenERP v7.

If you are only interested in payment you can use https://github.com/OCA/l10n-switzerland/tree/7.0/l10n_ch_sepa module instead for version 7.0.
