### ISSUE TITLE
[11] align l10n_ch_payment_slip 11 on 12

### ISSUE THREAD

**Issue by houssine78** [OCA/l10n-switzerland#543]
Hi there !

I'm wondering what is the best way to align code of l10n_ch_payment_slip 11 from the 12 after the change brought by this [PR](https://github.com/OCA/l10n-switzerland/pull/510).

The other changes has been done on 12 without being backported.

My first tought is to backport the actual version of 12 and propose it on 11 overriding the actual version on 11. But maybe I'm missing something ?

@yvaucher your inputs are more than welcome as I saw you've been highly active on this module.

Thanks.

**Comment by yvaucher** [comment]
@houssine78 late answer on this. But you might be interested that I currently have an intern demand to backport Swiss QR to v10. From there it should be a piece of cake to migrate it either to version 9.0 or version 11.0.

`l10n_ch_payment_slip` will slowly but surely be deprecated. I have no will to continue it's support.

`l10n_ch_payment_slip` have had multiple refactor and might be quite different on the different Odoo flavor, current state is not satisfactory in all of them to me, it works for some case but lack some features. Especially the ISR-B implementation which is flawed and confusing. (IMO mostly due to the Postfinance overly complicated ISR definition and not having dig enough in the specs soon enough).

My advice is to patch what you need on `l10n_ch_payment_slip` and wait to switch to QR Bill.

ISR payment slip is dead*, long live the QR-Bill.
(* ok not such drama as it will slowly retire till 2022)

**Comment by yvaucher** [comment]
Swiss QR-bill has been merged here: https://github.com/OCA/l10n-switzerland/tree/10.0/l10n_ch_qr_bill

For v11 it needs to be ported
For v12 we have to wait on Odoo to finalize it: https://github.com/odoo/odoo/pull/54427

**Comment by houssine78** [comment]
Hi @yvaucher so far we patched the l10n_ch_payment_slip but we'll have a look at the QR Bill for sure in a not that near futur.

Thanks a lot !
