### ISSUE TITLE
[11] remaining amount not write on ISR

### ISSUE THREAD

**Issue by brusly08** [OCA/l10n-switzerland#554]
Hello, 
 When I have invoice with a partial payment, how can I print a new ISR with the remaining amount and not the total amount ? 
Best regards,
Brusly

**Comment by yvaucher** [comment]
Hello @brusly08 ,

Can you state which version of Odoo you use and if you use l10n_ch official ISR or l10n_ch_payment_slip ?

Be also advised that since the 30th of June you can use Swiss QR-bill instead.

For v10:  https://github.com/OCA/l10n-switzerland/tree/10.0/l10n_ch_qr_bill
For v11 it needs to be ported
For v12 we have to wait on Odoo to finalize it: odoo/odoo#54427
For v13 it is available in `l10n_ch`
